[package]
name = "lightyear_connection"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Connection handling for the lightyear networking library"
repository = "https://github.com/cBournhonesque/lightyear"

[features]
default = ["std"]
std = ["lightyear_link/std", "lightyear_packet/std"]

[dependencies]
# local crates
lightyear_link.workspace = true
lightyear_packet.workspace = true

# utils
anyhow.workspace = true
bytes.workspace = true
cfg-if.workspace = true
hashbrown.workspace = true
serde.workspace = true
thiserror.workspace = true
tracing.workspace = true
chacha20poly1305.workspace = true

[lints]
workspace = true
