[package]
name = "avian_physics_new"
version = "0.0.0"
authors = ["Charles Bournhonesque <charlesbour@gmail.com>"]
edition = "2021"
publish = false

[features]
default = ["client", "gui", "server", "netcode", "udp"]
client = [
  "gui",
  "lightyear/client",
  "lightyear_examples_common_new/client"
]
gui = [
  "lightyear_examples_common_new/gui"
]
server = [
  "lightyear/server",
  "lightyear_examples_common_new/server"
]
netcode = [
  "lightyear_examples_common_new/netcode"
]
udp = [
  "lightyear_examples_common_new/udp",
  # udp requires std
  "lightyear/std",
  "lightyear/udp",
]

[dependencies]
lightyear = { workspace = true, features = [
  "interpolation",
  "prediction",
  "replication",
  "leafwing",
  "avian2d",
] }
lightyear_examples_common_new.workspace = true

leafwing-input-manager.workspace = true
avian2d = { workspace = true, features = [
  "2d",
  "f32",
  "parry-f32",
  "parallel",
  "serialize",
] }
serde.workspace = true
anyhow.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
bevy.workspace = true
rand.workspace = true
metrics-exporter-prometheus = { workspace = true, optional = true }

[lints]
workspace = true
