[package]
name = "spaceships_new"
version.workspace = true
authors = [
  "Charles Bournhonesque <charlesbour@gmail.com>",
  "Richard Jones <rj@metabrew.com>",
]
edition.workspace = true
publish = false

[features]
default = ["client", "gui", "server", "netcode", "udp"]
client = [
  "gui",
  "lightyear/client",
  "lightyear_examples_common_new/client"
]
gui = [
  "lightyear_examples_common_new/gui"
]
server = [
  "lightyear/server",
  "lightyear_examples_common_new/server"
]
netcode = [
  "lightyear_examples_common_new/netcode"
]
udp = [
  "lightyear_examples_common_new/udp",
  # udp requires std
  "lightyear/std",
  "lightyear/udp",
]

[dependencies]
lightyear = { workspace = true, features = [
  "interpolation",
  "prediction",
  "replication",
  "leafwing",
  "avian2d",
  "input_native", # Added based on simple_box_new
] }
lightyear_examples_common_new.workspace = true
metrics-exporter-prometheus = { workspace = true, optional = true }
leafwing-input-manager = { workspace = true, features = ["keyboard", "mouse"] }
avian2d = { workspace = true, features = [
  "2d",
  "f32",
  "parry-f32",
  "parallel",
  "serialize",
] }
serde.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
bevy.workspace = true
bevygap_client_plugin = { workspace = true, optional = true, features = [
  "matchmaker-tls",
] }

[lints]
workspace = true
