[package]
name = "lightyear_replication"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "IO primitives for the lightyear networking library"
repository = "https://github.com/cBournhonesque/lightyear"

[features]
default = ["std"]
std = [
    "bevy/std",
    "bytes/std",
    "serde/std",
    "lightyear_connection/std",
    "lightyear_transport/std",
    "lightyear_messages/std",
    "lightyear_serde/std",
    "lightyear_utils/std",
    "lightyear_core/std",
]
client = [
    "lightyear_connection/client",
]
server = [
    "lightyear_connection/server",
]

[dependencies]
lightyear_utils.workspace = true
lightyear_serde.workspace = true
lightyear_core.workspace = true
lightyear_connection.workspace = true
lightyear_messages.workspace = true
lightyear_transport.workspace = true

# utils
crossbeam-channel.workspace = true
hashbrown.workspace = true
smallvec.workspace = true
thiserror.workspace = true
tracing.workspace = true

# serde
serde.workspace = true
bytes.workspace = true

# bevy
bevy.workspace = true

[dev-dependencies]
test-log.workspace = true

[lints]
workspace = true
