[package]
name = "lightyear_shared"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "IO primitives for the lightyear networking library"
repository = "https://github.com/cBournhonesque/lightyear"

[features]
default = ["std"]
std = [
    "bevy/std",
    "bytes/std",
    "serde/std",
]

# io
crossbeam = ["dep:lightyear_crossbeam"]
udp = ["dep:lightyear_udp"]

[dependencies]
lightyear_utils.workspace = true
lightyear_serde.workspace = true
lightyear_core.workspace = true
lightyear_connection.workspace = true
lightyear_messages.workspace = true
lightyear_transport.workspace = true
lightyear_crossbeam = {workspace = true, optional = true }
lightyear_udp = {workspace = true, optional = true }
lightyear_steam = {workspace = true, optional= true}
lightyear_sync.workspace = true

# utils
tracing.workspace = true

# serde
serde.workspace = true
bytes.workspace = true

# bevy
bevy.workspace = true

[lints]
workspace = true
