[package]
name = "network_visibility"
version = "0.1.0"
authors = ["Charles Bournhonesque <charlesbour@gmail.com>"]
edition = "2021"
description = "Examples for the lightyearServer-client networking library for the Bevy game engine"
readme = "README.md"
repository = "https://github.com/cBournhonesque/lightyear"
keywords = ["bevy", "multiplayer", "networking", "netcode", "gamedev"]
categories = ["game-development", "network-programming"]
license = "MIT OR Apache-2.0"
publish = false

[features]
default = ["client", "gui", "server", "netcode", "udp"]
client = [
  "gui",
  "lightyear/client",
  "lightyear_examples_common_new/client"
]
gui = [
  "lightyear_examples_common_new/gui"
]
server = [
  "lightyear/server",
  "lightyear_examples_common_new/server"
]
netcode = [
  "lightyear_examples_common_new/netcode"
]
udp = [
  "lightyear_examples_common_new/udp",
  # udp requires std
  "lightyear/std",
  "lightyear/udp",
]

[dependencies]
lightyear = { workspace = true, features = [
  "input_native",
] }
lightyear_examples_common_new.workspace = true

leafwing-input-manager.workspace = true
serde.workspace = true
bevy.workspace = true

[lints]
workspace = true
