[package]
name = "lightyear_tests"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Setup for integration tests for the lightyear networking library"
repository = "https://github.com/cBournhonesque/lightyear"

[features]
default = [
    "std",
    "lightyear_new/interpolation"
]
std = [
    "bevy/std",
    "bytes/std",
    "serde/std",
    "lightyear_sync/std",
    "lightyear_messages/std",
    "lightyear_serde/std",
    "lightyear_transport/std",
]


[dependencies]
lightyear_new = { workspace = true, features = ["client", "server"]}
lightyear_macros.workspace = true
lightyear_utils.workspace = true
lightyear_serde.workspace = true
lightyear_transport.workspace = true
lightyear_core.workspace = true
lightyear_client = { workspace = true, features = ["crossbeam", "netcode"] }
lightyear_server = { workspace = true, features = ["crossbeam", "netcode"] }
lightyear_netcode = { workspace = true, features = ["client", "server", "test_utils"] }
lightyear_messages.workspace = true
lightyear_crossbeam.workspace = true
lightyear_connection = { workspace = true, features = ["client", "server"]}
lightyear_sync.workspace = true

# utils
cfg-if.workspace = true
tracing.workspace = true

# serde
serde.workspace = true
bytes.workspace = true

# bevy
bevy.workspace = true

[dev-dependencies]
test-log.workspace = true

[lints]
workspace = true
