[package]
name = "lightyear_steam"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Connection handling for the lightyear networking library"
repository = "https://github.com/cBournhonesque/lightyear"

[features]
default = ["std"]
std = [
    "lightyear_link/std",
    "lightyear_packet/std",
    "no_std_io2/std",
    "bytes/std",
    "chacha20poly1305/std",
]

[dependencies]
# local crates
lightyear_connection.workspace = true
lightyear_core.workspace = true
lightyear_link.workspace = true
lightyear_packet.workspace = true
lightyear_serde.workspace = true
lightyear_utils.workspace = true

# bevy
bevy.workspace = true

# no_std
no_std_io2.workspace = true

# utils
anyhow.workspace = true
bytes.workspace = true
cfg-if.workspace = true
hashbrown.workspace = true
serde.workspace = true
thiserror.workspace = true
tracing.workspace = true
rand.workspace = true
chacha20poly1305.workspace = true

[lints]
workspace = true
